### ISSUE TITLE
Error when changing font size of #sub

### ISSUE THREAD

**Issue by Amakaruk** [schlosser/substituteteacher.js#6] opened 2015-07-29 17:34 UTC
I tested this library at Codepen, and everything went well until I started changing the styles of the container Div (#sub). When I change the font size, the text gets cut in half from the bottom up.

See my example here:

http://codepen.io/Amakaruk/pen/YXRLbO

**Comment by schlosser** [comment] 2015-07-29 17:55
Thanks for submitting an issue!  I believe this is a duplicate of #5.  I hardcode the height of the words based on the height of the fallback text, so if the font size gets changed after the library initializes it breaks.   Thanks for the tip!

**Closed as completed** 2015-07-29 17:55 UTC
